<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/suite.py" name="unittest.suite._ErrorHolder-20191122150949" skipped="0" tests="1" time="0.000" timestamp="0001-01-01T00:00:00">
	<testcase classname="setUpClass (portscan_scan_tests" name="TestScan)" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'SimpleServers' object has no attribute 'pids'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/student/Documents/cs3280/projects/cs3280_project5/src/unittest/python/portscan_scan_tests.py", line 10, in setUpClass
    cls.servers.serveAll()
  File "/home/student/Documents/cs3280/projects/cs3280_project5/src/main/python/simpleservers.py", line 12, in serveAll
    self.pids.append(process.pid)
AttributeError: 'SimpleServers' object has no attribute 'pids'
]]>		</error>
		<system-out>
<![CDATA[(50000, 50001, 50002, 50003, 50004)
]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
