<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/suite.py" name="unittest.suite._ErrorHolder-20191122160455" skipped="0" tests="1" time="0.000" timestamp="0001-01-01T00:00:00">
	<testcase classname="setUpClass (portscan_scan_tests" name="TestScan)" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="name 'serve' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/student/Documents/cs3280/projects/cs3280_project5/src/unittest/python/portscan_scan_tests.py", line 10, in setUpClass
    cls.servers.start()
  File "/home/student/Documents/cs3280/projects/cs3280_project5/src/main/python/simpleservers.py", line 11, in start
    process = multiprocessing.Process(target=serve, args=(port,))
NameError: name 'serve' is not defined
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
